version: "3.8"

services:
  bot-cia-renato-torres:
    build: .
    container_name: bot-cia-renato-torres
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: bot-cia-renato-torres-redis
    restart: always
    ports:
      - "6379:6379"
